name = "kora/handle-mint"
version = "0.0.0"
compiler = "v1.0.29-alpha"
plutus = "v2"
license = "Apache-2.0"
description = "Aiken contracts for project 'kora/handle-mint'"

[repository]
user = "kora"
project = "handle-mint"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.9.0"
source = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "main"
source = "github"

[[dependencies]]
name = "aiken-lang/merkle-patricia-forestry"
version = "1.0.0"
source = "github"

[[dependencies]]
name = "SundaeSwap-finance/aicone"
version = "497e4dd59c1f1e02efacdee0c577ffcd030326bf"
source = "github"
